---
- name: my first playbook for testing
  hosts: all
  tasks:
    - name: printing task
      debug:
        msg: "Testing from anisble-server"

    tasks:
    - name: Second debug task
      debug:
        msg: "message calling debug module"
...