# ---
# - name: my first playbook for testing
#   hosts: all
#   tasks:
#     - name: printing task
#       debug:
#         msg: "Testing from anisble-server"
# ...

- name: Test one playbook
  hosts: all
  tasks:
    - name: shows the hosts distribution name
      debug:
        msg: "write any msg":{{anisble_user_gid}}
    - name: show multiple output in msg
      debug:
        msg: "writing any msg":{{ansible_env.LOGNAME}}